Create ERW proxy in the expected format (not yet working in workflow)
Note: if I add it to variabledefinitions, it gives an error when running the workflow, during the country-level downscaling:

```
 ~\..\..\concordia   cmip7_v0-4-0 ?1 ~6                                                     3.12.8 concordia python .\scripts\cmip7\driver_workflow_cmip7-fast-track.py
HERE: C:\Users\kikstra\Documents\GitHub\concordia
Running full workflow:   0%|                                                                 | 0/1 [00:00<?, ?it/s]workflow_cmip7-fast-track.py
Executing notebook.name='workflow_cmip7-fast-track.py' with parameters={'GRIDDING_VERSION': 'testing_erw_VL', 'marker_to_run': 'VL', 'SETTINGS_FILE': 'config_cmip7_v0-4-0.yaml', 'run_main': True, 'run_main_gridding': False, 'run_anthro_supplemental_voc': False, 'run_openburning_supplemental_voc': False, 'HISTORY_FILE': 'cmip7_history_countrylevel_251024.csv', 'DO_GRIDDING_ONLY_FOR_THESE_SPECIES': ['CO2']} from in_notebook=WindowsPath('C:/Users/kikstra/Documents/GitHub/concordia/notebooks-papermill/workflow_cmip7-fast-track_testing_erw_VL_unexecuted.ipynb'). Writing to output_notebook=WindowsPath('C:/Users/kikstra/Documents/GitHub/concordia/notebooks-papermill/workflow_cmip7-fast-track_testing_erw_VL.ipynb')
Passed unknown parameter: GRIDDING_VERSION
Passed unknown parameter: DO_GRIDDING_ONLY_FOR_THESE_SPECIES
Executing:  72%|██████████████████████████████████████████████▎                 | 73/101 [00:27<00:10,  2.70cell/s]
Running full workflow:   0%|                                                                 | 0/1 [00:27<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\kikstra\Documents\GitHub\concordia\scripts\cmip7\driver_workflow_cmip7-fast-track.py", line 178, in <module>
    main()
  File "C:\Users\kikstra\Documents\GitHub\concordia\scripts\cmip7\driver_workflow_cmip7-fast-track.py", line 137, in main
    run_notebook(notebook=notebook,
  File "C:\Users\kikstra\Documents\GitHub\concordia\src\concordia\cmip7\utils_papermill.py", line 24, in run_notebook
    pm.execute_notebook(in_notebook, output_notebook, parameters=parameters)
  File "C:\Users\kikstra\AppData\Local\miniconda3\envs\concordia\Lib\site-packages\papermill\execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "C:\Users\kikstra\AppData\Local\miniconda3\envs\concordia\Lib\site-packages\papermill\execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [44]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[44], line 1
----> 1 downscaled = workflow.harmonize_and_downscale() # For a 1 scenario, this takes about 50 seconds on Jarmo's DELL laptop.

File ~\Documents\GitHub\concordia\src\concordia\workflow.py:469, in WorkflowDriver.harmonize_and_downscale(self, variabledefs)
    462 if variabledefs is None:
    463     variabledefs = self.variabledefs
    465 return concat(
    466     skipnone(
    467         self.harmdown_globallevel(variabledefs),
    468         self.harmdown_regionlevel(variabledefs),
--> 469         self.harmdown_countrylevel(variabledefs),
    470     )
    471 )

File ~\Documents\GitHub\concordia\src\concordia\workflow.py:400, in WorkflowDriver.harmdown_countrylevel(self, variabledefs)
    398 harmonized = []
    399 downscaled = []
--> 400 for group in self.country_groups(variabledefs):
    401     regionmapping = self.regionmapping.filter(group.countries)
    402     missing_regions = set(self.regionmapping.data.unique()).difference(
    403         regionmapping.data.unique()
    404     )

File ~\Documents\GitHub\concordia\src\concordia\workflow.py:247, in WorkflowDriver.country_groups(self, variabledefs)
    227 # determine proxy weights for all related proxy variables
    228 # Uses:
    229 # - `self.proxies`: A dictionary mapping output variables to `ConcordiaProxy` objects,
   (...)
    239 # - `CountryGroup`: A named tuple containing `countries` and `variables` for harmonization and downscaling.
    240 # - `logger.info`: Logs information about generated country groups for debugging and tracking.
    241 regional_proxies = variabledefs.proxies
    242 variable_weights = [
    243     w.to_series()
    244     for w in dask.compute(
    245         *[
    246             proxy.weight["country"].sum("year")
--> 247             for output_variable, proxy in self.proxies.items()
    248             if output_variable in regional_proxies and "country" in proxy.weight
    249         ]
    250     )
    251 ]
    253 if not variable_weights:
    254     # No proxies, so all variables fall into one group with all countries
    255     country_groups = [(all_countries, variabledefs.index)]

File ~\AppData\Local\miniconda3\envs\concordia\Lib\functools.py:995, in cached_property.__get__(self, instance, owner)
    993 val = cache.get(self.attrname, _NOT_FOUND)
    994 if val is _NOT_FOUND:
    996     try:

    171 @cached_property
    173     context = GriddingContext(
    174         indexraster_country=self.indexraster_country,
    175         indexraster_region=self.indexraster_region,
    176         cell_area=self.indexraster_country.cell_area,
    177     )
    179     return {
--> 180         output_variable: ConcordiaProxy.from_variables(
    181             self.variabledefs.for_proxy(output_variable),
    182             context,
    183             self.settings.proxy_path,
    184         )
    185         for output_variable in self.variabledefs.proxies
    186     }

File ~\Documents\GitHub\concordia\src\concordia\grid.py:102, in ConcordiaProxy.from_variables(cls, df, context, proxy_dir)
     99 if df.pix.unique("gas").tolist() == ["TA"]:
    100     index_mappings["gas"] = pd.Series(["CO2"], ["TA"])
--> 102 return cls.from_files(
    103     name, paths, frozenset(df["griddinglevel"]), context, index_mappings
    104 )

File ~\AppData\Local\miniconda3\envs\concordia\Lib\site-packages\aneris\grid.py:192, in Proxy.from_files(cls, name, paths, levels, context, index_mappings)
    188     mapping = index_mappings.get(dim)
    189     if mapping is not None:
    190         proxy = (
    191             proxy.rename({dim: f"proxy_{dim}"})
--> 192             .sel({f"proxy_{dim}": xr.DataArray(mapping, dims=[dim])})
    193             .drop_vars(f"proxy_{dim}")
    194         )
    196 return cls(proxy, levels, context, name)

File ~\AppData\Local\miniconda3\envs\concordia\Lib\site-packages\xarray\core\dataarray.py:1683, in DataArray.sel(self, indexers, method, tolerance, drop, **indexers_kwargs)
   1567 def sel(
   1568     self,
   1569     indexers: Mapping[Any, Any] | None = None,
   (...)
   1573     **indexers_kwargs: Any,
   1574 ) -> Self:
   1575     """Return a new DataArray whose data is given by selecting index
   1576     labels along the specified dimension(s).
   1577
   (...)
   1681     Dimensions without coordinates: points
   1682     """
-> 1683     ds = self._to_temp_dataset().sel(
   1684         indexers=indexers,
   1685         drop=drop,
   1686         method=method,
   1687         tolerance=tolerance,
   1688         **indexers_kwargs,
   1689     )
   1690     return self._from_temp_dataset(ds)

File ~\AppData\Local\miniconda3\envs\concordia\Lib\site-packages\xarray\core\dataset.py:3249, in Dataset.sel(self, indexers, method, tolerance, drop, **indexers_kwargs)
   3181 """Returns a new dataset with each array indexed by tick labels
   3182 along the specified dimension(s).
   3183
   (...)
   3246
   3247 """
   3248 indexers = either_dict_or_kwargs(indexers, indexers_kwargs, "sel")
-> 3249 query_results = map_index_queries(
   3250     self, indexers=indexers, method=method, tolerance=tolerance
   3251 )
   3253 if drop:
   3254     no_scalar_variables = {}

File ~\AppData\Local\miniconda3\envs\concordia\Lib\site-packages\xarray\core\indexing.py:194, in map_index_queries(obj, indexers, method, tolerance, **indexers_kwargs)
    192         results.append(IndexSelResult(labels))
    193     else:
--> 194         results.append(index.sel(labels, **options))
    196 merged = merge_sel_results(results)
    198 # drop dimension coordinates found in dimension indexers
    199 # (also drop multi-index if any)
    200 # (.sel() already ensures alignment)

File ~\AppData\Local\miniconda3\envs\concordia\Lib\site-packages\xarray\core\indexes.py:801, in PandasIndex.sel(self, labels, method, tolerance)
    799     indexer = get_indexer_nd(self.index, label_array, method, tolerance)
    800     if np.any(indexer < 0):
--> 801         raise KeyError(f"not all values found in index {coord_name!r}")
    803 # attach dimension names and/or coordinates to positional indexer
    804 if isinstance(label, Variable):

KeyError: "not all values found in index 'proxy_sector'"

```